id: P000704
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:59.452813
source_metadata:
  id: bdr:W3CN6415
  title: བོད་དུ་རྒྱུན་མཐོང་གི་རང་བྱུང་གནོད་འཚེའི་སྐོར་གྱི་དྲི་བ།
  author: ''
  volumes:
    a5c4fb8de55c473aae8388cff02245d9:
      image_group_id: I3CN6417
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
