id: IDFCAEE83
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:19:59+00:00'
last_modified: '2022-06-07T12:42:17.403298+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6415
  title: བོད་དུ་རྒྱུན་མཐོང་གི་རང་བྱུང་གནོད་འཚེའི་སྐོར་གྱི་དྲི་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    '2716':
      image_group_id: I3CN6417
      title: ''
      total_pages: 112
      order: 1
      base_file: 2716.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
